export const data = {
  "location": {
    "name": "London",
    "region": "City of London, Greater London",
    "country": "United Kingdom",
    "lat": 51.52,
    "lon": -0.11,
    "tz_id": "Europe/London",
    "localtime_epoch": 1643797917,
    "localtime": "2022-02-02 10:31"
  },
  "current": {
    "last_updated_epoch": 1643796900,
    "last_updated": "2022-02-02 10:15",
    "temp_c": 11.0,
    "temp_f": 51.8,
    "is_day": 1,
    "condition": {
      "text": "Sunny",
      "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
      "code": 1000
    },
    "wind_mph": 13.6,
    "wind_kph": 22.0,
    "wind_degree": 280,
    "wind_dir": "W",
    "pressure_mb": 1023.0,
    "pressure_in": 30.21,
    "precip_mm": 0.0,
    "precip_in": 0.0,
    "humidity": 76,
    "cloud": 0,
    "feelslike_c": 9.3,
    "feelslike_f": 48.7,
    "vis_km": 10.0,
    "vis_miles": 6.0,
    "uv": 3.0,
    "gust_mph": 12.3,
    "gust_kph": 19.8
  },
  "forecast": {
    "forecastday": [
      {
        "date": "2022-02-02",
        "date_epoch": 1643760000,
        "day": {
          "maxtemp_c": 12.1,
          "maxtemp_f": 53.8,
          "mintemp_c": 7.7,
          "mintemp_f": 45.9,
          "avgtemp_c": 9.9,
          "avgtemp_f": 49.8,
          "maxwind_mph": 13.0,
          "maxwind_kph": 20.9,
          "totalprecip_mm": 0.0,
          "totalprecip_in": 0.0,
          "avgvis_km": 10.0,
          "avgvis_miles": 6.0,
          "avghumidity": 78.0,
          "daily_will_it_rain": 0,
          "daily_chance_of_rain": 0,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Partly cloudy",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
            "code": 1003
          },
          "uv": 1.0
        },
        "astro": {
          "sunrise": "07:38 AM",
          "sunset": "04:52 PM",
          "moonrise": "08:50 AM",
          "moonset": "06:24 PM",
          "moon_phase": "Waxing Crescent",
          "moon_illumination": "2"
        },
        "hour": [
          {
            "time_epoch": 1643760000,
            "time": "2022-02-02 00:00",
            "temp_c": 9.8,
            "temp_f": 49.6,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 13.0,
            "wind_kph": 20.9,
            "wind_degree": 284,
            "wind_dir": "WNW",
            "pressure_mb": 1022.0,
            "pressure_in": 30.18,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 79,
            "cloud": 41,
            "feelslike_c": 7.0,
            "feelslike_f": 44.6,
            "windchill_c": 7.0,
            "windchill_f": 44.6,
            "heatindex_c": 9.8,
            "heatindex_f": 49.6,
            "dewpoint_c": 6.3,
            "dewpoint_f": 43.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 20.4,
            "gust_kph": 32.8,
            "uv": 1.0
          },
          {
            "time_epoch": 1643763600,
            "time": "2022-02-02 01:00",
            "temp_c": 9.7,
            "temp_f": 49.5,
            "is_day": 0,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 12.1,
            "wind_kph": 19.4,
            "wind_degree": 289,
            "wind_dir": "WNW",
            "pressure_mb": 1022.0,
            "pressure_in": 30.18,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 81,
            "cloud": 92,
            "feelslike_c": 7.0,
            "feelslike_f": 44.6,
            "windchill_c": 7.0,
            "windchill_f": 44.6,
            "heatindex_c": 9.7,
            "heatindex_f": 49.5,
            "dewpoint_c": 6.5,
            "dewpoint_f": 43.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 18.8,
            "gust_kph": 30.2,
            "uv": 1.0
          },
          {
            "time_epoch": 1643767200,
            "time": "2022-02-02 02:00",
            "temp_c": 10.0,
            "temp_f": 50.0,
            "is_day": 0,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 10.3,
            "wind_kph": 16.6,
            "wind_degree": 283,
            "wind_dir": "WNW",
            "pressure_mb": 1022.0,
            "pressure_in": 30.18,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 80,
            "cloud": 100,
            "feelslike_c": 7.7,
            "feelslike_f": 45.9,
            "windchill_c": 7.7,
            "windchill_f": 45.9,
            "heatindex_c": 10.0,
            "heatindex_f": 50.0,
            "dewpoint_c": 6.7,
            "dewpoint_f": 44.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 16.1,
            "gust_kph": 25.9,
            "uv": 1.0
          },
          {
            "time_epoch": 1643770800,
            "time": "2022-02-02 03:00",
            "temp_c": 10.4,
            "temp_f": 50.7,
            "is_day": 0,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 11.0,
            "wind_kph": 17.6,
            "wind_degree": 274,
            "wind_dir": "W",
            "pressure_mb": 1021.0,
            "pressure_in": 30.16,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 80,
            "cloud": 95,
            "feelslike_c": 8.1,
            "feelslike_f": 46.6,
            "windchill_c": 8.1,
            "windchill_f": 46.6,
            "heatindex_c": 10.4,
            "heatindex_f": 50.7,
            "dewpoint_c": 7.1,
            "dewpoint_f": 44.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 16.8,
            "gust_kph": 27.0,
            "uv": 1.0
          },
          {
            "time_epoch": 1643774400,
            "time": "2022-02-02 04:00",
            "temp_c": 10.6,
            "temp_f": 51.1,
            "is_day": 0,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 11.2,
            "wind_kph": 18.0,
            "wind_degree": 275,
            "wind_dir": "W",
            "pressure_mb": 1021.0,
            "pressure_in": 30.15,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 77,
            "cloud": 99,
            "feelslike_c": 8.3,
            "feelslike_f": 46.9,
            "windchill_c": 8.3,
            "windchill_f": 46.9,
            "heatindex_c": 10.6,
            "heatindex_f": 51.1,
            "dewpoint_c": 6.8,
            "dewpoint_f": 44.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 17.4,
            "gust_kph": 28.1,
            "uv": 1.0
          },
          {
            "time_epoch": 1643778000,
            "time": "2022-02-02 05:00",
            "temp_c": 10.2,
            "temp_f": 50.4,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 12.5,
            "wind_kph": 20.2,
            "wind_degree": 275,
            "wind_dir": "W",
            "pressure_mb": 1021.0,
            "pressure_in": 30.16,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 79,
            "cloud": 42,
            "feelslike_c": 7.6,
            "feelslike_f": 45.7,
            "windchill_c": 7.6,
            "windchill_f": 45.7,
            "heatindex_c": 10.2,
            "heatindex_f": 50.4,
            "dewpoint_c": 6.7,
            "dewpoint_f": 44.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 19.2,
            "gust_kph": 31.0,
            "uv": 1.0
          },
          {
            "time_epoch": 1643781600,
            "time": "2022-02-02 06:00",
            "temp_c": 9.4,
            "temp_f": 48.9,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 12.5,
            "wind_kph": 20.2,
            "wind_degree": 274,
            "wind_dir": "W",
            "pressure_mb": 1022.0,
            "pressure_in": 30.17,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 82,
            "cloud": 47,
            "feelslike_c": 6.6,
            "feelslike_f": 43.9,
            "windchill_c": 6.6,
            "windchill_f": 43.9,
            "heatindex_c": 9.4,
            "heatindex_f": 48.9,
            "dewpoint_c": 6.5,
            "dewpoint_f": 43.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 19.2,
            "gust_kph": 31.0,
            "uv": 1.0
          },
          {
            "time_epoch": 1643785200,
            "time": "2022-02-02 07:00",
            "temp_c": 8.8,
            "temp_f": 47.8,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 11.9,
            "wind_kph": 19.1,
            "wind_degree": 273,
            "wind_dir": "W",
            "pressure_mb": 1022.0,
            "pressure_in": 30.17,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 84,
            "cloud": 22,
            "feelslike_c": 6.0,
            "feelslike_f": 42.8,
            "windchill_c": 6.0,
            "windchill_f": 42.8,
            "heatindex_c": 8.8,
            "heatindex_f": 47.8,
            "dewpoint_c": 6.3,
            "dewpoint_f": 43.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 17.9,
            "gust_kph": 28.8,
            "uv": 1.0
          },
          {
            "time_epoch": 1643788800,
            "time": "2022-02-02 08:00",
            "temp_c": 8.3,
            "temp_f": 46.9,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 10.3,
            "wind_kph": 16.6,
            "wind_degree": 281,
            "wind_dir": "WNW",
            "pressure_mb": 1022.0,
            "pressure_in": 30.19,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 86,
            "cloud": 31,
            "feelslike_c": 5.6,
            "feelslike_f": 42.1,
            "windchill_c": 5.6,
            "windchill_f": 42.1,
            "heatindex_c": 8.3,
            "heatindex_f": 46.9,
            "dewpoint_c": 6.0,
            "dewpoint_f": 42.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 15.4,
            "gust_kph": 24.8,
            "uv": 3.0
          },
          {
            "time_epoch": 1643792400,
            "time": "2022-02-02 09:00",
            "temp_c": 8.5,
            "temp_f": 47.3,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 8.7,
            "wind_kph": 14.0,
            "wind_degree": 281,
            "wind_dir": "WNW",
            "pressure_mb": 1023.0,
            "pressure_in": 30.21,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 83,
            "cloud": 59,
            "feelslike_c": 6.2,
            "feelslike_f": 43.2,
            "windchill_c": 6.2,
            "windchill_f": 43.2,
            "heatindex_c": 8.5,
            "heatindex_f": 47.3,
            "dewpoint_c": 5.8,
            "dewpoint_f": 42.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 12.3,
            "gust_kph": 19.8,
            "uv": 3.0
          },
          {
            "time_epoch": 1643796000,
            "time": "2022-02-02 10:00",
            "temp_c": 9.3,
            "temp_f": 48.7,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 8.3,
            "wind_kph": 13.3,
            "wind_degree": 274,
            "wind_dir": "W",
            "pressure_mb": 1023.0,
            "pressure_in": 30.22,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 78,
            "cloud": 40,
            "feelslike_c": 7.3,
            "feelslike_f": 45.1,
            "windchill_c": 7.3,
            "windchill_f": 45.1,
            "heatindex_c": 9.3,
            "heatindex_f": 48.7,
            "dewpoint_c": 5.7,
            "dewpoint_f": 42.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 11.0,
            "gust_kph": 17.6,
            "uv": 3.0
          },
          {
            "time_epoch": 1643799600,
            "time": "2022-02-02 11:00",
            "temp_c": 10.4,
            "temp_f": 50.7,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 9.6,
            "wind_kph": 15.5,
            "wind_degree": 269,
            "wind_dir": "W",
            "pressure_mb": 1024.0,
            "pressure_in": 30.22,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 73,
            "cloud": 36,
            "feelslike_c": 8.3,
            "feelslike_f": 46.9,
            "windchill_c": 8.3,
            "windchill_f": 46.9,
            "heatindex_c": 10.4,
            "heatindex_f": 50.7,
            "dewpoint_c": 5.7,
            "dewpoint_f": 42.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 11.9,
            "gust_kph": 19.1,
            "uv": 4.0
          },
          {
            "time_epoch": 1643803200,
            "time": "2022-02-02 12:00",
            "temp_c": 11.3,
            "temp_f": 52.3,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 9.8,
            "wind_kph": 15.8,
            "wind_degree": 272,
            "wind_dir": "W",
            "pressure_mb": 1023.0,
            "pressure_in": 30.22,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 68,
            "cloud": 36,
            "feelslike_c": 9.4,
            "feelslike_f": 48.9,
            "windchill_c": 9.4,
            "windchill_f": 48.9,
            "heatindex_c": 11.3,
            "heatindex_f": 52.3,
            "dewpoint_c": 5.7,
            "dewpoint_f": 42.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 11.9,
            "gust_kph": 19.1,
            "uv": 4.0
          },
          {
            "time_epoch": 1643806800,
            "time": "2022-02-02 13:00",
            "temp_c": 11.8,
            "temp_f": 53.2,
            "is_day": 1,
            "condition": {
              "text": "Cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
              "code": 1006
            },
            "wind_mph": 9.4,
            "wind_kph": 15.1,
            "wind_degree": 276,
            "wind_dir": "W",
            "pressure_mb": 1022.0,
            "pressure_in": 30.19,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 67,
            "cloud": 76,
            "feelslike_c": 10.1,
            "feelslike_f": 50.2,
            "windchill_c": 10.1,
            "windchill_f": 50.2,
            "heatindex_c": 11.8,
            "heatindex_f": 53.2,
            "dewpoint_c": 5.8,
            "dewpoint_f": 42.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 11.4,
            "gust_kph": 18.4,
            "uv": 3.0
          },
          {
            "time_epoch": 1643810400,
            "time": "2022-02-02 14:00",
            "temp_c": 12.0,
            "temp_f": 53.6,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 8.3,
            "wind_kph": 13.3,
            "wind_degree": 276,
            "wind_dir": "W",
            "pressure_mb": 1022.0,
            "pressure_in": 30.18,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 67,
            "cloud": 49,
            "feelslike_c": 10.6,
            "feelslike_f": 51.1,
            "windchill_c": 10.6,
            "windchill_f": 51.1,
            "heatindex_c": 12.0,
            "heatindex_f": 53.6,
            "dewpoint_c": 6.0,
            "dewpoint_f": 42.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 10.3,
            "gust_kph": 16.6,
            "uv": 4.0
          },
          {
            "time_epoch": 1643814000,
            "time": "2022-02-02 15:00",
            "temp_c": 12.1,
            "temp_f": 53.8,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 7.2,
            "wind_kph": 11.5,
            "wind_degree": 269,
            "wind_dir": "W",
            "pressure_mb": 1022.0,
            "pressure_in": 30.18,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 68,
            "cloud": 47,
            "feelslike_c": 10.9,
            "feelslike_f": 51.6,
            "windchill_c": 10.9,
            "windchill_f": 51.6,
            "heatindex_c": 12.1,
            "heatindex_f": 53.8,
            "dewpoint_c": 6.3,
            "dewpoint_f": 43.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 8.9,
            "gust_kph": 14.4,
            "uv": 4.0
          },
          {
            "time_epoch": 1643817600,
            "time": "2022-02-02 16:00",
            "temp_c": 11.6,
            "temp_f": 52.9,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 6.3,
            "wind_kph": 10.1,
            "wind_degree": 258,
            "wind_dir": "WSW",
            "pressure_mb": 1022.0,
            "pressure_in": 30.17,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 72,
            "cloud": 48,
            "feelslike_c": 10.5,
            "feelslike_f": 50.9,
            "windchill_c": 10.5,
            "windchill_f": 50.9,
            "heatindex_c": 11.6,
            "heatindex_f": 52.9,
            "dewpoint_c": 6.6,
            "dewpoint_f": 43.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 8.3,
            "gust_kph": 13.3,
            "uv": 4.0
          },
          {
            "time_epoch": 1643821200,
            "time": "2022-02-02 17:00",
            "temp_c": 10.7,
            "temp_f": 51.3,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 6.0,
            "wind_kph": 9.7,
            "wind_degree": 250,
            "wind_dir": "WSW",
            "pressure_mb": 1022.0,
            "pressure_in": 30.18,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 77,
            "cloud": 47,
            "feelslike_c": 9.5,
            "feelslike_f": 49.1,
            "windchill_c": 9.5,
            "windchill_f": 49.1,
            "heatindex_c": 10.7,
            "heatindex_f": 51.3,
            "dewpoint_c": 6.8,
            "dewpoint_f": 44.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 8.7,
            "gust_kph": 14.0,
            "uv": 1.0
          },
          {
            "time_epoch": 1643824800,
            "time": "2022-02-02 18:00",
            "temp_c": 10.2,
            "temp_f": 50.4,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 5.8,
            "wind_kph": 9.4,
            "wind_degree": 246,
            "wind_dir": "WSW",
            "pressure_mb": 1022.0,
            "pressure_in": 30.17,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 81,
            "cloud": 34,
            "feelslike_c": 9.0,
            "feelslike_f": 48.2,
            "windchill_c": 9.0,
            "windchill_f": 48.2,
            "heatindex_c": 10.2,
            "heatindex_f": 50.4,
            "dewpoint_c": 7.0,
            "dewpoint_f": 44.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 8.5,
            "gust_kph": 13.7,
            "uv": 1.0
          },
          {
            "time_epoch": 1643828400,
            "time": "2022-02-02 19:00",
            "temp_c": 9.7,
            "temp_f": 49.5,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 5.6,
            "wind_kph": 9.0,
            "wind_degree": 244,
            "wind_dir": "WSW",
            "pressure_mb": 1022.0,
            "pressure_in": 30.17,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 84,
            "cloud": 29,
            "feelslike_c": 8.4,
            "feelslike_f": 47.1,
            "windchill_c": 8.4,
            "windchill_f": 47.1,
            "heatindex_c": 9.7,
            "heatindex_f": 49.5,
            "dewpoint_c": 7.2,
            "dewpoint_f": 45.0,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 7.8,
            "gust_kph": 12.6,
            "uv": 1.0
          },
          {
            "time_epoch": 1643832000,
            "time": "2022-02-02 20:00",
            "temp_c": 8.7,
            "temp_f": 47.7,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 6.3,
            "wind_kph": 10.1,
            "wind_degree": 244,
            "wind_dir": "WSW",
            "pressure_mb": 1022.0,
            "pressure_in": 30.17,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 86,
            "cloud": 36,
            "feelslike_c": 7.1,
            "feelslike_f": 44.8,
            "windchill_c": 7.1,
            "windchill_f": 44.8,
            "heatindex_c": 8.7,
            "heatindex_f": 47.7,
            "dewpoint_c": 6.5,
            "dewpoint_f": 43.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 9.6,
            "gust_kph": 15.5,
            "uv": 1.0
          },
          {
            "time_epoch": 1643835600,
            "time": "2022-02-02 21:00",
            "temp_c": 8.3,
            "temp_f": 46.9,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 6.7,
            "wind_kph": 10.8,
            "wind_degree": 244,
            "wind_dir": "WSW",
            "pressure_mb": 1022.0,
            "pressure_in": 30.16,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 86,
            "cloud": 26,
            "feelslike_c": 6.5,
            "feelslike_f": 43.7,
            "windchill_c": 6.5,
            "windchill_f": 43.7,
            "heatindex_c": 8.3,
            "heatindex_f": 46.9,
            "dewpoint_c": 6.1,
            "dewpoint_f": 43.0,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 10.1,
            "gust_kph": 16.2,
            "uv": 1.0
          },
          {
            "time_epoch": 1643839200,
            "time": "2022-02-02 22:00",
            "temp_c": 8.0,
            "temp_f": 46.4,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 6.9,
            "wind_kph": 11.2,
            "wind_degree": 241,
            "wind_dir": "WSW",
            "pressure_mb": 1021.0,
            "pressure_in": 30.16,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 84,
            "cloud": 26,
            "feelslike_c": 6.0,
            "feelslike_f": 42.8,
            "windchill_c": 6.0,
            "windchill_f": 42.8,
            "heatindex_c": 8.0,
            "heatindex_f": 46.4,
            "dewpoint_c": 5.4,
            "dewpoint_f": 41.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 10.1,
            "gust_kph": 16.2,
            "uv": 1.0
          },
          {
            "time_epoch": 1643842800,
            "time": "2022-02-02 23:00",
            "temp_c": 7.7,
            "temp_f": 45.9,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 6.9,
            "wind_kph": 11.2,
            "wind_degree": 242,
            "wind_dir": "WSW",
            "pressure_mb": 1021.0,
            "pressure_in": 30.15,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 81,
            "cloud": 20,
            "feelslike_c": 5.7,
            "feelslike_f": 42.3,
            "windchill_c": 5.7,
            "windchill_f": 42.3,
            "heatindex_c": 7.7,
            "heatindex_f": 45.9,
            "dewpoint_c": 4.7,
            "dewpoint_f": 40.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 10.1,
            "gust_kph": 16.2,
            "uv": 1.0
          }
        ]
      }
    ]
  }
}